package com.reactnativevoisekappextension.utils

object Constants {
  const val CALLER_BLOCK_KEY = "CALLER_BLOCK_LIST"
  const val CALLER_OPTIONS_KEY = "CALLER_OPTIONS_KEY"
  const val REQUEST_DATA_KEY = "REQUEST_DATA_KEY"
  const val OPTION_BLOCK_CALL_ON_BLACK_LIST = "OPTION_BLOCK_CALL_ON_BLACK_LIST"
  const val OPTION_CAN_CHECK_CALL_STATE = "OPTION_CAN_CHECK_CALL_STATE"
  const val OPTION_CAN_REQUEST_ROLE = "OPTION_CAN_REQUEST_ROLE"
  const val REQUEST_ID_BECOME_CALL_SCREENER = 7273
  const val PHONE_NEEDED_PERM = 7467
  const val VOISEK_NOT_CHANNEL_ID = "VOISEK_NOT_CHANNEL_ID"
  const val VOISEK_NOT_CHANNEL_NAME = "Voisek Notifications"
  const val VOISEK_NOT_CHANNEL_DESC = "Voisek Notification System"
  const val VOISEK_NOT_ID = 1
  const val VOISEK_NOT_FOREGROUND_ID = 1
  const val VOISEK_ACTION_FOREGROUND_SERVICE_START = "VOISEK_ACTION_FOREGROUND_SERVICE_START"
  const val VOISEK_ACTION_FOREGROUND_SERVICE_STOP = "VOISEK_ACTION_FOREGROUND_SERVICE_STOP"
  const val VOISEK_ACTION_FOREGROUND_SHOW_NOT = "VOISEK_ACTION_FOREGROUND_SHOW_NOT"
}
