package com.reactnativevoisekappextension.utils

object Constants {
  const val CALLER_BLOCK_KEY = "CALLER_BLOCK_LIST"
  const val CALLER_OPTIONS_KEY = "CALLER_OPTIONS_KEY"
  const val REQUEST_DATA_KEY = "REQUEST_DATA_KEY"
  const val OPTION_BLOCK_CALL_ON_BLACK_LIST = "OPTION_BLOCK_CALL_ON_BLACK_LIST"
  const val OPTION_CAN_CHECK_CALL_STATE = "OPTION_CAN_CHECK_CALL_STATE"
  const val OPTION_CAN_REQUEST_ROLE = "OPTION_CAN_REQUEST_ROLE"
  const val REQUEST_ID_BECOME_CALL_SCREENER = 7273
  const val PHONE_NEEDED_PERM = 7467
  const val NOT_SHARED_PREF_DATA = "NOT_SHARED_PREF_DATA"
  const val NOT_CHANNEL_ID = "NOT_CHANNEL_ID"
  const val NOT_CHANNEL_NAME_KEY = "NOT_CHANNEL_NAME_KEY"
  const val NOT_CHANNEL_NAME = "Voisek Notifications"
  const val NOT_CHANNEL_DESC_KEY = "NOT_CHANNEL_DESC_KEY"
  const val NOT_CHANNEL_DESC = "Voisek Notification System"
  const val NOT_NAME_LISTENING_INIT_KEY = "NOT_NAME_LISTENING_INIT_KEY"
  const val NOT_NAME_LISTENING_INIT = "Voisek System"
  const val NOT_DESC_LISTENING_INIT_KEY = "NOT_DESC_LISTENING_INIT_KEY"
  const val NOT_DESC_LISTENING_INIT = "Voisek System verifying call"
  const val NOT_NAME_LISTENING_END_KEY = "NOT_NAME_LISTENING_END_KEY"
  const val NOT_NAME_LISTENING_END = "Voisek System"
  const val NOT_DESC_LISTENING_END_KEY = "NOT_DESC_LISTENING_END_KEY"
  const val NOT_DESC_LISTENING_END = "Voisek System complete verification"
  const val NOT_ID = 1
  const val NOT_FOREGROUND_ID = 1
  const val NOT_ACTION_FOREGROUND_SERVICE_START = "NOT_ACTION_FOREGROUND_SERVICE_START"
  const val NOT_ACTION_FOREGROUND_SERVICE_STOP = "NOT_ACTION_FOREGROUND_SERVICE_STOP"
  const val NOT_ACTION_FOREGROUND_SHOW_NOT = "NOT_ACTION_FOREGROUND_SHOW_NOT"
}
